Public class verificationObject {
    public String phoneNumber{get;set;}
    public String memberNumber{get;set;}
    public String SSN{get;set;}
    public String SSNMatch {get;set;}
    public String DOB{get;set;}
    public String ICardNumber{get;set;}
    public String MMN{get;set;}
    public String CardNumber{get;set;}
    public String Pin{get;set;}
    public String fieldnametocheck{get; set;} 
    public String Email{get;set;}
    
}