public class WiresConstant {
    
    //-------------------------------- Approval Status-------------------------------------------//
    
	 
     public static final string ApprovalStatus_GoodFundsReview='Good Funds Review';
     public static final string ApprovalStatus_PendingForApproval='Pending for Approval';
     public static final string ApprovalStatus_PendingForSecondApproval='Pending for Second Approval';
     public static final string ApprovalStatus_FraudReview='Fraud Review';
     public static final string ApprovalStatus_Approved='Approved';
     public static final string ApprovalStatus_Rejected='Rejected';
     public static final string ApprovalStatus_PendingForMemberReview='Pending for Member Review';
     public static final string ApprovalStatus_Cancelled='Cancelled';
     public static final string ApprovalStatus_FraudRejected='Fraud Rejected';
     public static final string ApprovalStatus_Recurring='Recurring';
     public static final string ApprovalStatus_DSExpired='DS Expired';
     public static final string ApprovalStatus_DSDeclined='DS Declined';
    
    
    //--------------------------------Wire Transaction Source---------------------------------------------//
    
    public static final string Source_Branch='Branch';
    public static final string Source_OnlineBanking='Online Banking';
    
    //--------------------------------Wire Groups ---------------------------------------------//
    
    public static final string Branch_Group_A='Branch_Group_A';
    public static final string Branch_Group_B='Branch_Group_B';
    public static final string Branch_Group_C='Branch_Group_C';
    public static final string Branch_Group_D='Branch_Group_D';
    public static final string Branch_Group_E='Branch_Group_E';
    
    public static final string Online_Group_A='WIRES_Online_Group_A';
    public static final string Online_Group_B='WIRES_Online_Group_B';
    public static final string Online_Group_C='WIRES_Online_Group_C';
    public static final string Online_Group_D='WIRES_Online_Group_D';
    public static final string Online_Group_E='WIRES_Online_Group_E';
    
    //--------------------------------Wires Frequency---------------------------------------------//
    
    public static final string OneTime='One - Time';
    public static final string Reccuring='Recurring';
    
    //--------------------------------Wires RecordTypes---------------------------------------------//
    
    public static final string Branch_Domestic_1_Time='Branch Domestic 1 Time';
    public static final string Branch_Domestic_Recurring='Branch Domestic Recurring';
    public static final string Online_Domestic_1_Time= 'Online Domestic 1 Time';
    public static final string Online_Domestic_Recurring='Online Domestic Recurring';
}