public class WiresConstant {
    
    //-------------------------------- Approval Status-------------------------------------------//
    
	 public static final string ApprovalStatus_GoodFundsCheckFailed='Good Funds Check Failed';
     public static final string ApprovalStatus_PendingForApproval='Pending for Approval';
     public static final string ApprovalStatus_PendingForSecondApproval='Pending for Second Approval';
     public static final string ApprovalStatus_FraudReview='Fraud Review';
     public static final string ApprovalStatus_Approved='Approved';
     public static final string ApprovalStatus_Rejected='Rejected';
     public static final string ApprovalStatus_PendingForMemberReview='Pending for Member Review';
    
    
    //--------------------------------Wire Transaction Source---------------------------------------------//
    
    public static final string Source_Branch='Branch';
    public static final string Source_OnlineBanking='Online Banking';
    
    //--------------------------------Wire Groups ---------------------------------------------//
    
    public static final string Branch_Group_A='Branch_Group_A';
    public static final string Branch_Group_B='Branch_Group_B';
    public static final string Branch_Group_C='Branch_Group_C';
    public static final string Branch_Group_D='Branch_Group_D';
    public static final string Branch_Group_E='Branch_Group_E';
    
    public static final string Online_Group_A='WIRES_Online_Group_A';
    public static final string Online_Group_B='WIRES_Online_Group_B';
    public static final string Online_Group_C='WIRES_Online_Group_C';
    public static final string Online_Group_D='WIRES_Online_Group_D';
    public static final string Online_Group_E='WIRES_Online_Group_E';
    
}